---
- name: Check if lens is already installed
  ansible.builtin.command:
    cmd: pacman -Q lens
  register: lens_installed
  changed_when: false
  failed_when: false

- name: Install lens via yay
  ansible.builtin.command:
    cmd: yay -S --noconfirm --sudoflags "-A" lens
  environment:
    SUDO_ASKPASS: "{{ yay_askpass }}"
  when: lens_installed.rc != 0
  changed_when: true
