---
- name: Install zsh
  community.general.pacman:
    name: zsh
    state: present
  become: true

- name: Check if oh-my-zsh is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_dir

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not ohmyzsh_dir.stat.exists
  changed_when: true

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
